### PR TITLE
Stack safe version

### LINKED ISSUE #12: Stack safety
I think it should be fairly easy to make this stack safe, the only problem is the existential eliminator prevents it from _actually_ being tail recursive. We need to make it unsafe to make it safe :P

### PR DESCRIPTION
**Pull request by safareli**
fixes #12

It can be optimize even further but generally i'm satisfied with performance we have now (https://github.com/typelevel/cats/pull/1921)

### CODE REVIEW

**Comment by safareli** [comment]
@natefaubion @paf31 @ethul @garyb I have added tests and i'm confident that it's correct. So this is ready for review. 🎉

**Comment by ethul** [comment]
Thanks so much for your work on this! Your proposal looks great!

I am still working through the changes, but I am wondering if you happen to have any performance numbers that we can use to compare this to the current implementation and the implementations in #9 and #10. 

Would you be willing to include graphs, as a comment in this PR, like the ones in the other PRs? Thanks again!

**Comment by safareli** [comment]
I remember you had a lib ps-freeap-benchmarks or something but i can't find it any more, do you have a link to it?

**Comment by ethul** [comment]
Yes! Good call. Are you thinking of this?
https://github.com/ethul/purescript-benchmarks

**Comment by safareli** [comment]
yes it's that, remembered different name :d

**Comment by safareli** [comment]
I have added this version of FreeAp to the repo and did benchmarks https://github.com/ethul/purescript-benchmarks/pull/1/files

Now I'm testing only "New" "Day" and "Safe" versions for big inputs (until first two crash :p)

**Comment by ethul** [comment]
Great! Thanks for doing the benchmarks.

**Comment by safareli** [comment]
I have added some larger benchmarks https://github.com/ethul/purescript-benchmarks/pull/1/commits/04a8762d90dcc32cdf4d944235a760a7f498a252

To sum up it has almost the same performance as thunk based version here https://github.com/ethul/purescript-freeap/pull/9

**Comment by ethul** [comment]
This all looks great! Thanks again for your work on this PR.

**Pull request merged**
