### PR TITLE
Update for PureScript 0.15

### PR DESCRIPTION
**Pull request by thomashoneyman**
Hi @ethul 👋

This PR updates `freeap` for PureScript 0.15, which supports ES modules in the FFI. Along the way I switched you from Travis CI to GitHub Actions as the Travis script isn't running anymore.

As with previous compiler releases, I'm updating `freeap` because Halogen depends on this library. If you'd like, I can help maintain this library strictly for compiler releases so you don't have to do anything each time we make a new one. If not, that's totally fine too!

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Tests pass:

```console
❯ npx pulp@16.0.0-1 test                    
* Building project in /Users/trh/Desktop/purescript-freeap
           Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  
* Build successful.
* Running tests...

valid case:
(Right Joe Smith 28)

empty last name:
(Left "Last name: Invalid NES")

invalid age:
(Left "Age: Invalid Int")

analyze:
(Right "BABABABABABABABABABAB")

stack safety:
(Right "safe for 100000 node")

laws:


Checking laws of FreeAp instances...

Checking 'Reflexivity' law for Eq
1000/1000 test(s) passed.
Checking 'Symmetry' law for Eq
1000/1000 test(s) passed.
Checking 'Transitivity' law for Eq
1000/1000 test(s) passed.
Checking 'Negation' law for Eq
1000/1000 test(s) passed.
Checking 'Identity' law for Functor
1000/1000 test(s) passed.
Checking 'Composition' law for Functor
1000/1000 test(s) passed.
Checking 'Associative composition' law for Apply
1000/1000 test(s) passed.
Checking 'Identity' law for Applicative
1000/1000 test(s) passed.
Checking 'Composition' law for Applicative
1000/1000 test(s) passed.
Checking 'Homomorphism' law for Applicative
1000/1000 test(s) passed.
Checking 'Interchange' law for Applicative
1000/1000 test(s) passed.
* Tests OK.
```

**Comment by garyb** [comment]
Bump!

**Comment by ethul** [comment]
This looks great! Thanks so much for the PR. Much appreciated and apologies for the delay!

**Comment by garyb** [comment]
No problem! Thanks for taking care of the library :smile:

**Comment by ethul** [comment]
Most welcome!

**Pull request merged**
